"""Presentation-only data for the navigable UI mockups.

The shapes intentionally mirror future view models. Route functions should replace these
constants with application-service results when the corresponding backend slice is built.
"""

CURRENT_USER = {
    "id": 1,
    "display_name": "김민준",
    "login_id": "minjun.kim",
    "email": "minjun.kim@example.com",
    "organization": "플랫폼개발팀",
    "system_role": "시스템 관리자",
    "initials": "김민",
}

PROJECTS = [
    {
        "key": "OPS",
        "name": "운영 플랫폼 고도화",
        "description": "사내 운영 도구와 자동화 파이프라인을 개선합니다.",
        "role": "프로젝트 관리자",
        "color": "violet",
        "open_count": 24,
        "member_count": 9,
        "updated": "오늘 14:32",
        "progress": 68,
        "active": True,
    },
    {
        "key": "WEB",
        "name": "고객 포털 개편",
        "description": "고객 포털의 정보 구조와 주요 업무 흐름을 재설계합니다.",
        "role": "프로젝트 사용자",
        "color": "blue",
        "open_count": 17,
        "member_count": 12,
        "updated": "어제 17:10",
        "progress": 42,
        "active": True,
    },
    {
        "key": "DATA",
        "name": "데이터 품질 개선",
        "description": "핵심 지표의 정합성과 데이터 운영 프로세스를 개선합니다.",
        "role": "프로젝트 사용자",
        "color": "emerald",
        "open_count": 8,
        "member_count": 6,
        "updated": "9월 14일",
        "progress": 81,
        "active": True,
    },
]

TICKETS = [
    {
        "key": "OPS-142",
        "project_key": "OPS",
        "type": "Task",
        "title": "배포 승인 흐름에 검토 단계 추가",
        "description": (
            "운영 배포 전에 서비스 담당자와 보안 담당자가 순서대로 검토할 수 있도록 "
            "승인 흐름을 확장합니다."
        ),
        "status": "진행중",
        "status_code": "progress",
        "priority": "Critical",
        "priority_code": "critical",
        "assignee": "김민준",
        "assignee_initials": "김민",
        "creator": "이수진",
        "epic": "OPS-120 · 운영 안정성 개선",
        "parent": None,
        "due": "2026.09.18",
        "due_tone": "danger",
        "updated": "12분 전",
        "version": 7,
        "subtasks_done": 2,
        "subtasks_total": 4,
        "dependency": "OPS-131",
    },
    {
        "key": "OPS-139",
        "project_key": "OPS",
        "type": "Task",
        "title": "첨부파일 악성 확장자 정책 정리",
        "description": "운영 환경에서 허용할 확장자와 MIME type 정책을 확정합니다.",
        "status": "등록",
        "status_code": "todo",
        "priority": "Major",
        "priority_code": "major",
        "assignee": "박서연",
        "assignee_initials": "박서",
        "creator": "김민준",
        "epic": "OPS-120 · 운영 안정성 개선",
        "parent": None,
        "due": "2026.09.22",
        "due_tone": "normal",
        "updated": "1시간 전",
        "version": 3,
        "subtasks_done": 0,
        "subtasks_total": 2,
        "dependency": None,
    },
    {
        "key": "OPS-136",
        "project_key": "OPS",
        "type": "Subtask",
        "title": "세션 만료 시나리오 통합 테스트",
        "description": "세션 만료와 비활성 사용자 차단 시나리오를 통합 테스트로 검증합니다.",
        "status": "보류",
        "status_code": "hold",
        "priority": "Minor",
        "priority_code": "minor",
        "assignee": "최유진",
        "assignee_initials": "최유",
        "creator": "김민준",
        "epic": "OPS-101 · 인증 기반 정비",
        "parent": "OPS-128",
        "due": "2026.09.25",
        "due_tone": "normal",
        "updated": "어제",
        "version": 4,
        "subtasks_done": 0,
        "subtasks_total": 0,
        "dependency": None,
    },
    {
        "key": "OPS-131",
        "project_key": "OPS",
        "type": "Task",
        "title": "감사 로그 이벤트 카탈로그 정의",
        "description": "사용자와 프로젝트 주요 변경에서 남길 감사 이벤트를 정의합니다.",
        "status": "완료",
        "status_code": "done",
        "priority": "Major",
        "priority_code": "major",
        "assignee": "정도윤",
        "assignee_initials": "정도",
        "creator": "이수진",
        "epic": "OPS-120 · 운영 안정성 개선",
        "parent": None,
        "due": "2026.09.15",
        "due_tone": "muted",
        "updated": "9월 15일",
        "version": 9,
        "subtasks_done": 3,
        "subtasks_total": 3,
        "dependency": None,
    },
    {
        "key": "OPS-125",
        "project_key": "OPS",
        "type": "Task",
        "title": "운영 알림 채널 정책 검토",
        "description": "후속 범위에서 사용할 운영 알림 채널과 책임 범위를 검토합니다.",
        "status": "취소",
        "status_code": "cancelled",
        "priority": "Trivial",
        "priority_code": "trivial",
        "assignee": "미지정",
        "assignee_initials": "—",
        "creator": "박서연",
        "epic": "Epic 없음",
        "parent": None,
        "due": "—",
        "due_tone": "muted",
        "updated": "9월 11일",
        "version": 2,
        "subtasks_done": 0,
        "subtasks_total": 0,
        "dependency": None,
    },
]

MENTIONS = [
    {
        "actor": "이수진",
        "actor_initials": "이수",
        "project": "운영 플랫폼 고도화",
        "ticket": "OPS-142",
        "excerpt": "@김민준 승인 단계별 실패 처리도 이번 범위에 포함될까요?",
        "time": "24분 전",
    },
    {
        "actor": "박서연",
        "actor_initials": "박서",
        "project": "고객 포털 개편",
        "ticket": "WEB-87",
        "excerpt": "검색 필터 정책 검토를 부탁드립니다.",
        "time": "2시간 전",
    },
]

MEMBERS = [
    {
        "name": "김민준",
        "initials": "김민",
        "login_id": "minjun.kim",
        "organization": "플랫폼개발팀",
        "role": "프로젝트 관리자",
        "tickets": 7,
        "active": True,
    },
    {
        "name": "이수진",
        "initials": "이수",
        "login_id": "sujin.lee",
        "organization": "서비스기획팀",
        "role": "프로젝트 관리자",
        "tickets": 5,
        "active": True,
    },
    {
        "name": "박서연",
        "initials": "박서",
        "login_id": "seoyeon.park",
        "organization": "보안팀",
        "role": "프로젝트 사용자",
        "tickets": 4,
        "active": True,
    },
    {
        "name": "최유진",
        "initials": "최유",
        "login_id": "yujin.choi",
        "organization": "QA팀",
        "role": "프로젝트 사용자",
        "tickets": 3,
        "active": True,
    },
    {
        "name": "정도윤",
        "initials": "정도",
        "login_id": "doyun.jung",
        "organization": "SRE팀",
        "role": "프로젝트 사용자",
        "tickets": 2,
        "active": True,
    },
]

USERS = [
    {
        **member,
        "email": f"{member['login_id']}@example.com",
        "system_role": "시스템 관리자" if index == 0 else "일반 사용자",
    }
    for index, member in enumerate(MEMBERS)
]

ORGANIZATION_TREE = [
    {"name": "테크놀로지 본부", "key": "TECH", "count": 27, "children": [
        {"name": "플랫폼개발팀", "key": "PLATFORM", "count": 8},
        {"name": "SRE팀", "key": "SRE", "count": 6},
        {"name": "QA팀", "key": "QA", "count": 5},
    ]},
    {"name": "프로덕트 본부", "key": "PRODUCT", "count": 19, "children": [
        {"name": "서비스기획팀", "key": "PLANNING", "count": 7},
        {"name": "디자인팀", "key": "DESIGN", "count": 5},
    ]},
    {"name": "경영지원 본부", "key": "CORP", "count": 12, "children": []},
]

TRASH_TICKETS = [
    {
        "key": "OPS-118",
        "type": "Epic",
        "title": "레거시 모니터링 정리",
        "deleted_by": "이수진",
        "deleted_at": "2026.09.12",
        "purge_at": "2026.10.12",
        "children": 6,
    },
    {
        "key": "OPS-104",
        "type": "Task",
        "title": "사용하지 않는 배포 스크립트 제거",
        "deleted_by": "김민준",
        "deleted_at": "2026.09.08",
        "purge_at": "2026.10.08",
        "children": 2,
    },
]
